trigger:
- main
- master
- develop
- feature/*

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: 'BuildClient'
    displayName: 'Build job'

    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'bermtecshared'
          repository: 'dotnetdemo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
  