# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: 'Demo'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  repository: 'walmartpayment'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'ACRDocker'
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |         
            $(Build.BuildNumber)

- stage: 'Deploy'
  jobs:
  - deployment: "Dev"
    displayName: Deploy to AKS
    pool:
      name: 'Demo'
    variables: 
      namespace: 'walmartdev'
      k8sconnection: 'kubewalmartdev'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self          
          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              kubernetesServiceConnection: $(k8sconnection)
              action: deploy
              namespace: $(namespace)
              manifests: manifests/deployment.yaml|manifests/service.yaml
              arguments: '-n=walmartdev'
  