# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
   vmImage: 'ubuntu-latest'

variables:
  repository: 'bermtecpayment'
  namespace: 'bermtecpayment'
  k8sconnection: 'k8sbermtec'
  imagePullSecret: 'test'
  containerRegistry: 'bermtecshared'
  isMain: false

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistry)
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            latest
            1.0.$(Build.BuildId)

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: 'manifests'
          path: 'manifests'

- stage: 'Deploy'
  displayName: 'Deployment to Dev'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS  
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
           - task: DownloadPipelineArtifact@2
             displayName: 'Download Manifests'
             inputs:
                artifactName: 'manifests'
                downloadPath: '$(System.ArtifactsDirectory)/manifests'

           - task: KubernetesManifest@0
             displayName: Create imagePullSecret
             inputs:
                kubernetesServiceConnection: $(k8sconnection)
                action: createSecret
                secretName: $(imagePullSecret)
                namespace: $(namespace)
                dockerRegistryEndpoint: $(containerRegistry)
              
           - task: KubernetesManifest@0
             displayName: Deploy
             inputs:
              kubernetesServiceConnection: $(k8sconnection)
              action: deploy
              namespace: $(namespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yaml
                $(System.ArtifactsDirectory)/manifests/Service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              arguments: '-n=bermtecpayment'

- stage: 'Deploy_To_Test'
  displayName: 'Deployment to Test'
  dependsOn: 'Deploy'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS  
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
           - task: DownloadPipelineArtifact@2
             displayName: 'Download Manifests'
             inputs:
                artifactName: 'manifests'
                downloadPath: '$(System.ArtifactsDirectory)/manifests'

           - task: Bash@3
             displayName: 'Replace token'
             inputs:
                 targetType: 'inline'
                 script: 'sed "s/dev/test/i" $(System.ArtifactsDirectory)/manifests/deployment.yaml'
              
           - task: KubernetesManifest@0
             displayName: Deploy
             inputs:
              kubernetesServiceConnection: $(k8sconnection)
              action: deploy
              namespace: $(namespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yaml
                $(System.ArtifactsDirectory)/manifests/Service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              arguments: '-n=bermtecpayment'

- stage: 'Deploy_To_Prod'
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: 'Deployment to Prod'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS  
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
           - task: DownloadPipelineArtifact@2
             displayName: 'Download Manifests'
             inputs:
                artifactName: 'manifests'
                downloadPath: '$(System.ArtifactsDirectory)/manifests'
              
           - task: KubernetesManifest@0
             displayName: Deploy
             inputs:
              kubernetesServiceConnection: $(k8sconnection)
              action: deploy
              namespace: $(namespace)
              manifests: |
                $(System.ArtifactsDirectory)/manifests/deployment.yaml
                $(System.ArtifactsDirectory)/manifests/Service.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              arguments: '-n=bermtecpayment'
  