trigger:
- main
- develop
- feature/*
- bugfix/*

pool:
  name: 'demo'
  demands: docker

variables:
  repository: 'azacrshared'

stages:
- stage: 'Build'
  jobs:
  - job: 'DockerBuild'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: '$(repository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'