# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- feature/*
- master

pool:
  name: 'Demo'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  repository: 'walmartpayment'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    # - script: dotnet build --configuration $(buildConfiguration)
    #   displayName: 'dotnet build $(buildConfiguration)'

    # - script: dotnet publish -f $(dotNetFramework) -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    #   displayName: Publish Project 

    # - task: Npm@1
    #   displayName: 'Client Tests'
    #   inputs:
    #     command: 'custom'
    #     workingDir: 'ClientApp'
    #     customCommand: 'run test'
    
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'

      - task: Docker@2
        inputs:
          containerRegistry: 'ACRDocker'
          repository: '$(repository)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |         
            $(Build.BuildNumber)


- stage: 'Deploy'
  jobs:
  - deployment: ""
    displayName: Deploy to AKS
 
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
          
            - task: KubernetesManifest@0
              displayName: Deploy
              inputs:
                kubernetesServiceConnection: 'k8swalmart'
                action: deploy
                namespace: walmart
                manifests: deployment-azure.yaml
                containers: |
                  azacrshared.azurecr.io/walmartpayment:$(Build.BuildNumber)
                arguments: '-n=walmart'
  